### ISSUE TITLE
Process's are staying alive despite kill attempt.

### ISSUE THREAD

**Issue by rlindskog** [DylanPiercey/spawn-server-webpack-plugin#1]
@DylanPiercey

Great project, I've always loved the idea of spawning servers in memory, and you've come up with an elegant solution.

My project [solit](https://github.com/rlindskog/solit) uses spawn-server-webpack-plugin for in-memory HMR for express projects, while abstracting babel/webpack boilerplate.

I don't know if this is an issue with my project or spawn-server-webpack-plugin, but sometimes when I save and the server refreshes, previous process's aren't killed successfully. I found a solution which involves keeping an array of process's that are not meant to be alive, and killing them in the `SpawnServer.close` method, then removing them from that list.

[Here is a replication](https://github.com/rlindskog/solit-example)

I'll submit a PR of the solution you can take a look at too.

**Comment by DylanPiercey** [comment]
@rlindskog thanks for looking into this. I am curious how exactly your solution improves the situation. Currently it is setup on [here]() to close the existing process before starting a new one. However I may have noticed this issue in development but attributed to webpack messing up compilation.

I'll dig a little deeper though, it may have something to do with done being called in rapid succession.
I think if this is the case a better solution would be to alter https://github.com/DylanPiercey/spawn-server-webpack-plugin/blob/master/index.js#L88 to not set `this.process = null` until after `process.once('exit'` ensuring that any new process waits for the existing one if webpack fires `done` in rapid succession.

Curious what your thoughts are on that. Depending on what you have found I'll release a patch that switches to this approach since it's more robust anyway.

**Comment by DylanPiercey** [comment]
@rlindskog I am releasing a patch right now which I think will resolve the issue. It should also now skip quick renders and only start the most recent build. Let me know if this works for you.

**Comment by rlindskog** [comment]
@DylanPiercey Still having a bit of trouble.  I managed to get it working by using `process.kill(this.process.process.pid)` instead of `this.process.kill()`.  [Looks like piping had a similar problem](https://github.com/mdlawson/piping/pull/12)

**Comment by DylanPiercey** [comment]
Strange it doesn't look like that's a part of the cluster API? The signature is `process.kill(SIGNAL: string)`.

**Comment by rlindskog** [comment]
[The other process.kill](https://nodejs.org/api/process.html#process_process_kill_pid_signal)

**Comment by DylanPiercey** [comment]
🤦‍♂️ Thanks for pointing that out. Can you confirm this change resolves the issue? If so I'll happily accept a PR.

**Comment by rlindskog** [comment]
Yes it does!

**Comment by DylanPiercey** [comment]
Fixed 🎉! Thanks for your help!

**Comment by rlindskog** [comment]
Thank you for the sweet project!

**Comment by DylanPiercey** [comment]
No problem. If you have any other pain points or ideas just shoot them my way 😄.
